/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package financial.transaction.analyser

import financial.transaction.analyser.cli.CommandLineInterface

fun main(args: Array<String>) {
    CommandLineInterface().main(args)
}
